version: '2.20.3'

services:
    app:
      build: .
      command: npm start
      ports:
        - "3000:3000"
      volumes:
        - .:/usr/app
    db: 
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=guiaperguntar
      ports:
        - "3306:3306"
      volumes:
        - .:/usr/database:/app/db